src/Entity/Song.php
<?php

namespace App\Entity;

use App\Repository\SongRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: SongRepository::class)]
class Song
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(length: 255)]
    private ?string $band = null;

    /**
     * @var Collection<int, Playlist>
     */
    #[ORM\ManyToMany(targetEntity: Playlist::class, inversedBy: 'songs')]
    private Collection $playlists;

    #[ORM\Column]
    #[Assert\LessThan(value: 60, message: 'Please enter a number between 0 and 59')]
    private ?int $minDuration = null;

    #[ORM\Column]
    #[Assert\LessThan(value: 60, message: 'Please enter a number between 0 and 59')]
    private ?int $secDuration = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $filename = null;

    public function __construct(private readonly string $targetDirectory)
    {
        $this->playlists = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getBand(): ?string
    {
        return $this->band;
    }

    public function setBand(string $band): static
    {
        $this->band = $band;

        return $this;
    }

    /**
     * @return Collection<int, Playlist>
     */
    public function getPlaylists(): Collection
    {
        return $this->playlists;
    }

    public function addPlaylist(Playlist $playlist): static
    {
        if (!$this->playlists->contains($playlist)) {
            $this->playlists->add($playlist);
        }

        return $this;
    }

    public function removePlaylist(Playlist $playlist): static
    {
        $this->playlists->removeElement($playlist);

        return $this;
    }

    public function getMinDuration(): ?int
    {
        return $this->minDuration;
    }

    public function setMinDuration(int $minDuration): static
    {
        $this->minDuration = $minDuration;

        return $this;
    }

    public function getSecDuration(): ?int
    {
        return $this->secDuration;
    }

    public function setSecDuration(int $secDuration): static
    {
        $this->secDuration = $secDuration;

        return $this;
    }

    public function getFilePath(): ?string
    {
        $fileName = $this->filename;

        if($fileName) {
            return $this->targetDirectory . '/' . $fileName;
        }

        return 'defaults/backup-image.jpg';
    }

    public function getFilename(): ?string
    {
        return $this->filename;
    }

    public function setFilename(?string $filename): static
    {
        $this->filename = $filename;

        return $this;
    }
}

src/Form/SongType.php
<?php

namespace App\Form;

use App\Entity\Playlist;
use App\Entity\Song;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class SongType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title')
            ->add('band')
            ->add('minDuration', IntegerType::class, [
                'rounding_mode' => \NumberFormatter::ROUND_HALFUP,
                'label' => 'minutes'
            ])
            ->add('secDuration', IntegerType::class, [
                'rounding_mode' => \NumberFormatter::ROUND_HALFUP,
                'label' => 'seconds'
            ])


            ->add('image', FileType::class, [
                'label' => 'Upload a picture for this song',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '2M',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                            'image/webp'
                        ],
                        'mimeTypesMessage' => 'Please upload a valid image in the following fomats: jpeg, png, webp',
                    ])
                ]
            ])
        ;

        if(empty($options['playlist'])) {
            $builder
                ->add('playlists', EntityType::class, [
                    'class' => Playlist::class,
                    'choice_label' => 'id',
                    'multiple' => true,
                ])
            ;
        }
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Song::class,
            'playlist' => Playlist::class
        ]);
    }
}

src/Controller/SongController.php
<?php

namespace App\Controller;

use App\Entity\Playlist;
use App\Entity\Song;
use App\Form\SongType;
use App\Repository\PlaylistRepository;
use App\Repository\SongRepository;
use App\Service\FileUploader;
use Doctrine\ORM\EntityManagerInterface;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/song')]
class SongController extends AbstractController
{
    #[Route('/new/{id}', name: 'app_add_song', methods: ['GET', 'POST'])]
    public function new(
        Playlist $playlist,
        Request $request,
        EntityManagerInterface $em,
        FileUploader $fileUploader
    ): Response
    {
        $song = new Song();
        $song->addPlaylist($playlist);

        $form = $this->createForm(SongType::class, $song, [
            'playlist' => $playlist
        ]);

        $imgFile = $form->get('image')->getData();

        if ($form->isSubmitted() && $form->isValid()) {
            $form->handleRequest($request);

            if($imgFile) {
                $fileName = $fileUploader->handleImageUpload($imgFile);
                $song->setFilename($fileName);
            }

            $em->persist($song);
            $em->flush();

            $playlistName = $playlist->getName();

            $this->addFlash('success', "New song has been added to the playlist $playlistName");

            return $this->redirectToRoute('app_playlists');
        }

        return $this->render('song/_form.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/{playlist}/edit/{id}', name: 'app_edit_song', methods: ['GET', 'POST'])]
    public function edit(
        Playlist $playlist,
        Song $song,
        Request $request,
        EntityManagerInterface $em,
        $targetDirectory,
        FileUploader $fileUploader
    ): Response
    {
        $form = $this->createForm(SongType::class, $song, [
            'playlist' => $playlist
        ]);

        if($song->getFilename()) {
            //$song->setFilename(new File($targetDirectory.'/'.$song->getFilename()));
            $form->get('image')->setData(new File($targetDirectory.'/'.$song->getFilename()));
        }

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $imgFile = $form->get('image')->getData();

            if($imgFile) {
                $fileName = $fileUploader->handleImageUpload($imgFile);
                $song->setFilename($fileName);
            }

            $em->persist($song);
            $em->flush();

            $songTitle = $song->getTitle();

            $this->addFlash('success', "The song '$songTitle' has been updated.");

            return $this->redirectToRoute('app_playlists');
        }

        return $this->render('song/_form.html.twig', [
            'form' => $form,
        ]);
    }

    #[Route('/show/{id}', name: 'app_show_song', methods: ['GET'])]
    public function show(Song $song, SongRepository $songRepository)
    {
        $playlists = $song->getPlaylists();
        $filteredPlayLists = $playlists->filter(fn($playlist) => $playlist->getUser() === $this->getUser());

        return $this->render('song/show.html.twig', [
            'song' => $song,
            'filteredPlayLists' => $filteredPlayLists,
        ]);
    }

    #[Route('/{id}', name: 'app_delete_song', methods: 'POST')]
    public function delete(Request $request, Song $song, EntityManagerInterface $em): Response
    {
        if($this->isCsrfTokenValid('delete'.$song->getId(), $request->request->get('_token'))) {
            $em->remove($song);
            $em->flush();
        }

        return $this->redirectToRoute('app_playlists');
    }
}

templates/song/_delete_form.html.twig
<form method="post" action="{{ path('app_delete_song', {'id': song.id }) }}" onsubmit="return confirm('Are you sure, you want to delete that song?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ song.id) }}">
    <button class="btn btn-sm btn-danger">
        <i class="fa-solid fa-trash"></i>
    </button>
</form>

templates/song/_form.html.twig
{% extends 'base.html.twig' %}

{% block title %}Playlist form{% endblock %}

{% block body %}

    <div class="my-5">
        {{ form_errors(form) }}

        {{ form_start(form) }}
            {{ form_row(form.title) }}
            {{ form_row(form.band) }}
            <div class="mb-1">Duration:</div>
            <div class="row mb-2">
                <div class="col">
                    {{ form_row(form.minDuration) }}
                </div>
                <div class="col">
                    {{ form_row(form.secDuration) }}
                </div>
            </div>
            {{ form_row(form.image) }}
            <button type="submit" class="btn btn-outline-success">{{ 'edit' in app.request.pathinfo ? 'edit' : 'create' }}</button>
        {{ form_end(form) }}
    </div>

{% endblock %}

templates/song/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SongController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>/var/www/html/src/Controller/SongController.php</code></li>
        <li>Your template at <code>/var/www/html/templates/song/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

templates/song/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SongController!{% endblock %}

{% block body %}
    <h1 class="lead">{{ song.title }}</h1>

    <div class="container">
        <div class="row">
            <div class="col-12 col-md-7">
                <ul>
                    <li>{{ song.band }}</li>
                    <li>{{ song.minDuration }}:{{ song.secDuration }} Min.</li>
                </ul>
                <h5>This song occures in your following playlists:</h5>
                <ul>
                    {% for playlist in filteredPlayLists %}
                        <li>
                            {# a href="{{ path('app_show_playlist', { 'id': playlist.id }) }}">{{ playlist.name }}</a> #}
                            {{ playlist.name }}
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-12 col-md-5">
                <img src="{{ asset(song.filePath) }}">
            </div>
        </div>
    </div>

{% endblock %}